name: Test Workflow

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Echo test
        run: echo "Workflow is working!"